apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: test-workflow
                arguments:
                  parameters:
                  - name: repo
                  - name: revision
                  - name: name
                  - name: branch

                templates:
                - name: test-workflow
                  steps:
                  - - name: checkout
                      template: checkout
                  - - name: webhook
                      template: webhook
                      arguments:
                        parameters:
                        - name: webhook-template
                          value: "{{steps.checkout.outputs.parameters.webhook-template}}"
                        - name: webhook-name
                          value: "{{webhook.name}}"
                        - name: repo
                          value: "{{workflow.parameters.repo}}"
                        - name: revision
                          value: "{{workflow.parameters.revision}}"
                        - name: name
                          value: "{{workflow.parameters.name}}"
                        - name: branch
                          value: "{{workflow.parameters.branch}}"
                        artifacts:
                        - name: source
                          from: "{{steps.checkout.outputs.artifacts.source}}"